<?php

/**
 * This is the model base class for the table "payment_status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PaymentStatus".
 *
 * Columns in table "payment_status" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $caption
 *
 */
abstract class BasePaymentStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'payment_status';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PaymentStatus|PaymentStatuses', $n);
	}

	public static function representingColumn() {
		return 'caption';
	}

	public function rules() {
		return array(
			array('caption', 'required'),
			array('caption', 'length', 'max'=>255),
			array('id, caption', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'caption' => Yii::t('app', 'Caption'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('caption', $this->caption, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
