<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'btn-cancel' => 'Cancel',
  'btn-close' => 'Close',
  'btn-create' => 'Create',
  'btn-delete' => 'Delete',
  'btn-download' => 'Download',
  'btn-edit' => 'Edit',
  'btn-edit-tooltip' => 'Edit tooltip',
  'btn-forgot-password' => 'Forgot password',
  'btn-login' => 'Login',
  'btn-new' => 'New',
  'btn-no-caption' => '(no caption)',
  'btn-preview' => 'Preview',
  'btn-remove' => 'Remove',
  'btn-save' => 'Save',
  'btn-sign-up' => 'Sign up',
  'btn-submit' => 'Submit',
  'menu-sign-in' => 'Sign in',
  'menu-sign-out' => 'Sign out',
  'menu-sign-up' => 'Sign up',
  'btn-forgot-password' => 'Forgot password',
	'btn-design' => 'Design',
	'btn-preview' => 'Preview',	
	'btn-export' => 'Export',
	'btn-add-file' => 'Add File'	,
	'btn-end-process' => 'End process',	
);
