<?php

/* /views/art/md5form.twig */
class __TwigTemplate_caead64f7298b2e255118c8bf3085620 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->blocks = array(
            'dialogHeader' => array($this, 'block_dialogHeader'),
            'dialogBody' => array($this, 'block_dialogBody'),
            'dialogFooter' => array($this, 'block_dialogFooter'),
            'onReady' => array($this, 'block_onReady'),
        );
    }

    protected function doGetParent(array $context)
    {
        return $this->env->resolveTemplate($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "viewPath", array(0 => "dialog"), "method"));
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $this->getParent($context)->display($context, array_merge($this->blocks, $blocks));
    }

    // line 7
    public function block_dialogHeader($context, array $blocks = array())
    {
        // line 8
        echo "<h3>MD5 information</h3>
";
    }

    // line 11
    public function block_dialogBody($context, array $blocks = array())
    {
        // line 12
        echo "\t";
        if ($this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model"), "hasErrors", array(), "method")) {
            // line 13
            echo "\t<div class=\"row\">
\t\t<div class=\"col-sm-10 col-sm-offset-1 alert alert-danger\">\t\t\t
\t\t\t";
            // line 15
            echo $this->getAttribute((isset($context["html"]) ? $context["html"] : null), "errorSummary", array(0 => $this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model")), "method");
            echo "
\t\t</div>
\t</div>
\t";
        }
        // line 18
        echo "\t
\t
\t<div class=\"row\">\t
\t\t<div class=\"col-sm-10 col-sm-offset-1\">
\t\t\t<p>
\t\t\t\tThe MD5 check is a way to check that the file is not corrupted during the move from the original machine to
\t\t\t\tthe FTP server and finaly to the storage. The MD5 can be generated by a program on 
\t\t\t\tWindows (<a href=\"http://www.winmd5.com/\" target=\"_blank\">winmd5</a>) or on the Mac
\t\t\t\t(<a href=\"http://md5.soft32.com/\" target=\"_blank\">md5</a>).<br/>
\t\t\t\tThe master file is checked after it has been uploaded and before it's being processed. \t\t\t\t
\t\t\t</p>
\t\t\t<p>
\t\t\t\tBecause of the HUGE size of the files, the processing can take a long type. So be patient.\t\t\t
\t\t\t</p>
\t\t\t<hr>
\t\t\t<fieldset>
\t\t\t\t<div class='row form-group'>
\t\t\t\t\t<div class=\"col-xs-5\">File on the server:</div>
\t\t\t\t\t<div class=\"col-xs-7\">
\t\t\t\t\t\t";
        // line 37
        if ($this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model"), "hasResource")) {
            // line 38
            echo "\t\t\t\t\t\t";
            echo twig_escape_filter($this->env, (($this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model", array(), "any", false, true), "storage_md5", array(), "any", true, true)) ? (_twig_default_filter($this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model", array(), "any", false, true), "storage_md5"), YiiTranslate("app", "Master file not yet scanned"))) : (YiiTranslate("app", "Master file not yet scanned"))), "html", null, true);
            echo "
\t\t\t\t\t\t";
        } else {
            // line 40
            echo "\t\t\t\t\t\t";
            echo twig_escape_filter($this->env, (($this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model", array(), "any", false, true), "storage_md5", array(), "any", true, true)) ? (_twig_default_filter($this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model", array(), "any", false, true), "storage_md5"), YiiTranslate("app", "No information"))) : (YiiTranslate("app", "No information"))), "html", null, true);
            echo "
\t\t\t\t\t\t";
        }
        // line 42
        echo "\t\t\t\t\t\t<button 
\t\t\t\t\t\t\t\tid=\"id-rescan\"
\t\t\t\t\t\t\t\thref=\"";
        // line 44
        echo twig_escape_filter($this->env, $this->getAttribute((isset($context["App"]) ? $context["App"] : null), "createUrl", array(0 => "art/md5generate", 1 => array("id" => $this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model"), "id"))), "method"), "html", null, true);
        echo "\" \t\t\t\t\t\t\t 
\t\t\t\t\t\t\t\tclass=\"btn btn-info\">";
        // line 45
        echo twig_escape_filter($this->env, YiiTranslate("app", "Calculate MD5 of file"), "html", null, true);
        echo "</button>
\t\t\t\t\t</div>
\t\t\t\t</div>
\t\t\t\t
\t\t\t\t<div id=\"msg-not-equal\" class=\"row\" ";
        // line 49
        if (($this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model"), "storage_md5") == $this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model"), "original_md5"))) {
            echo " style=\"display:none\" ";
        }
        echo ">
\t\t\t\t\t<div class=\"col-sm-10 col-sm-offset-1 alert alert-danger\">\t\t\t
\t\t\t\t\t\tThe file has been corrupted during transport. The MD5's of the files do NOT match
\t\t\t\t\t</div>
\t\t\t\t</div>
\t\t\t\t
\t\t\t\t<form id=\"form-md5\" method=\"POST\" action=\"";
        // line 55
        echo twig_escape_filter($this->env, $this->getAttribute((isset($context["this"]) ? $context["this"] : null), "createUrl", array(0 => "art/md5", 1 => array("id" => $this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model"), "id"))), "method"), "html", null, true);
        echo "\">\t\t
\t\t\t\t\t<div class='row form-group'>
\t\t\t\t\t\t<div class=\"col-xs-5\"><label>MD5 of uploaded file<br>This is generate by external software</label></div>
\t\t\t\t\t\t<div class=\"col-xs-7\">
\t\t\t\t\t\t<input id=\"id-original\" type=\"text\" value=\"";
        // line 59
        echo twig_escape_filter($this->env, $this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model"), "original_md5"), "html", null, true);
        echo "\" name=Art[original_md5]\"
\t\t\t\t\t\t\t\t\t style=\"width:95%\"><br />
\t\t\t\t\t\t</div>
\t\t\t\t\t</div>
\t\t\t\t\t<div class='row form-group'>
\t\t\t\t\t\t<div class=\"col-xs-7 col-xs-offset-5\">
\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">
\t\t\t\t\t\t\t";
        // line 66
        if ($this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model"), "original_md5")) {
            // line 67
            echo "\t\t\t\t\t\t\t";
            echo twig_escape_filter($this->env, YiiTranslate("app", "Update md5"), "html", null, true);
            echo "
\t\t\t\t\t\t\t";
        } else {
            // line 69
            echo "\t\t\t\t\t\t\t";
            echo twig_escape_filter($this->env, YiiTranslate("app", "Set md5"), "html", null, true);
            echo "
\t\t\t\t\t\t\t";
        }
        // line 71
        echo "\t\t\t\t\t\t</button>
\t\t\t\t\t\t</div>\t\t
\t\t\t\t\t</div>\t\t
\t\t\t\t</form>
\t\t\t</fieldset>
\t\t</div>\t\t\t\t\t
\t</div>
";
    }

    // line 80
    public function block_dialogFooter($context, array $blocks = array())
    {
        // line 81
        echo "\t<button type=\"button\" class=\"btn btn-default btn-close action-close\" data-dismiss=\"modal\">";
        echo twig_escape_filter($this->env, YiiTranslate("button", "btn-close"), "html", null, true);
        echo "</button>
";
    }

    // line 84
    public function block_onReady($context, array $blocks = array())
    {
        // line 85
        echo "\t
\t";
        // line 86
        echo twig_escape_filter($this->env, $this->getAttribute((isset($context["this"]) ? $context["this"] : null), "registerPackage", array(0 => "ajaxForm", 1 => array("isAjax" => true, "executeAfterLoad" => (((((((((("
\t\tvar optionsUpload = {
\t\t\ttarget : '#id-modal-body',
\t\t\tsuccess : processResponse
\t\t};
\t\t\$('#form-md5').ajaxForm(optionsUpload);\t\t

\t\tvar optionsSelect = {
\t\t\ttarget : '#id-modal-body',
\t\t\tsuccess : processResponse
\t\t};

\t\t\$('#form-select').ajaxForm(optionsSelect);\t\t\t

\t\t\$('#id-rescan').on('click', function() {
\t\t\tconsole.log('starting rescan');
\t\t\t\$.get('" . $this->getAttribute((isset($context["this"]) ? $context["this"] : null), "createUrl", array(0 => "art/md5generate", 1 => array("id" => $this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model"), "id"), "refresh" => $this->getAttribute((isset($context["util"]) ? $context["util"] : null), "unique", array(), "method"))), "method")) . "',
\t\t\t\tprocessResponse\t
\t\t\t)
\t\t});

\t\t\$('#id-original').on('keyup paste', function() {
\t\t\tif ('") . $this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model"), "storage_md5")) . "' == \$('#id-original').val()) {
\t\t\t\t\$('#msg-not-equal').hide();
\t\t\t} else {
\t\t\t\t\$('#msg-not-equal').show();
\t\t\t}\t\t\t\t
\t\t\tconsole.log('change to ' + \$('#id-original').val(), '") . $this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model"), "storage_md5")) . "');
\t\t});

\t\tfunction processResponse(responseText, statusText, xhr, \$form) 
\t\t{
\t\t\tif (responseText == 'ok') {/* ok: load information in a div */
\t\t\t\talert('did not expect to get an ok');
\t\t\t} else if (responseText = 'md5') {
\t\t\t\talert('The master files is marked for md5 generating');
\t\t\t\twindow.location = '") . $this->getAttribute((isset($context["this"]) ? $context["this"] : null), "createUrl", array(0 => "art/files", 1 => array("id" => $this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model"), "id"), "refresh" => $this->getAttribute((isset($context["util"]) ? $context["util"] : null), "unique", array(), "method"))), "method")) . "';
\t\t\t} else\tif (responseText == 'url') {/* ok, but open an other page */
\t\t\t\t\$('#id-modal-body').html('');
\t\t\t\twindow.location = '") . $this->getAttribute((isset($context["this"]) ? $context["this"] : null), "createUrl", array(0 => "art/files", 1 => array("id" => $this->getAttribute($this->getAttribute((isset($context["this"]) ? $context["this"] : null), "model"), "id"), "refresh" => $this->getAttribute((isset($context["util"]) ? $context["util"] : null), "unique", array(), "method"))), "method")) . "';
\t\t\t}\telse {
\t\t\t\t\$('#id-modal-body').html(responseText);
\t\t\t}
\t\t};\t
\t"))), "method"), "html", null, true);
        // line 130
        echo "
\t
\t\$('.action-close').on('click', function() {
\t\t\$('#id-modal').modal('hide');
\t});
\t
\t";
        // line 136
        echo twig_escape_filter($this->env, (isset($context["parent"]) ? $context["parent"] : null), "html", null, true);
        echo "
";
    }

    public function getTemplateName()
    {
        return "/views/art/md5form.twig";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  227 => 136,  219 => 130,  173 => 86,  170 => 85,  167 => 84,  160 => 81,  157 => 80,  146 => 71,  140 => 69,  134 => 67,  132 => 66,  122 => 59,  115 => 55,  104 => 49,  97 => 45,  93 => 44,  89 => 42,  83 => 40,  77 => 38,  75 => 37,  54 => 18,  47 => 15,  43 => 13,  40 => 12,  37 => 11,  32 => 8,  29 => 7,);
    }
}
