<?php

/**
 * This is the model base class for the table "resource_multi_rel".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResourceMultiRel".
 *
 * Columns in table "resource_multi_rel" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $master_id
 * @property integer $child_id
 * @property string $sort_key
 *
 */
abstract class BaseResourceMultiRel extends TwigActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'resource_multi_rel';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ResourceMultiRel|ResourceMultiRels', $n);
	}

	public static function representingColumn() {
		return 'sort_key';
	}

	public function rules() {
		return array(
			array('master_id, child_id', 'numerical', 'integerOnly'=>true),
			array('sort_key', 'length', 'max'=>255),
			array('master_id, child_id, sort_key', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, master_id, child_id, sort_key', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'master_id' => Yii::t('app', 'Master'),
			'child_id' => Yii::t('app', 'Child'),
			'sort_key' => Yii::t('app', 'Sort Key'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('master_id', $this->master_id);
		$criteria->compare('child_id', $this->child_id);
		$criteria->compare('sort_key', $this->sort_key, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
