<?php

/**
 * This is the model base class for the table "resource_type_field".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResourceTypeField".
 *
 * Columns in table "resource_type_field" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $ref
 * @property string $name
 * @property string $title
 * @property integer $type
 * @property string $options
 * @property integer $order_by
 * @property integer $keywords_index
 * @property integer $partial_index
 * @property integer $resource_type
 * @property string $resource_column
 * @property integer $display_field
 * @property integer $use_for_similar
 * @property string $iptc_equiv
 * @property string $display_template
 * @property string $tab_name
 * @property integer $required
 * @property string $smart_theme_name
 * @property string $exiftool_field
 * @property integer $advanced_search
 * @property integer $simple_search
 * @property string $help_text
 * @property integer $display_as_dropdown
 * @property integer $external_user_access
 * @property string $autocomplete_macro
 * @property integer $hide_when_uploading
 * @property integer $hide_when_restricted
 * @property string $value_filter
 * @property string $exiftool_filter
 * @property integer $omit_when_copying
 * @property string $tooltip_text
 * @property string $regexp_filter
 * @property integer $sync_field
 *
 */
abstract class BaseResourceTypeField extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'resource_type_field';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ResourceTypeField|ResourceTypeFields', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('type, order_by, keywords_index, partial_index, resource_type, display_field, use_for_similar, required, advanced_search, simple_search, display_as_dropdown, external_user_access, hide_when_uploading, hide_when_restricted, omit_when_copying, sync_field', 'numerical', 'integerOnly'=>true),
			array('name, resource_column, tab_name', 'length', 'max'=>50),
			array('title, regexp_filter', 'length', 'max'=>400),
			array('iptc_equiv', 'length', 'max'=>20),
			array('smart_theme_name, exiftool_field', 'length', 'max'=>200),
			array('options, display_template, help_text, autocomplete_macro, value_filter, exiftool_filter, tooltip_text', 'safe'),
			array('name, title, type, options, order_by, keywords_index, partial_index, resource_type, resource_column, display_field, use_for_similar, iptc_equiv, display_template, tab_name, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, sync_field', 'default', 'setOnEmpty' => true, 'value' => null),
			array('ref, name, title, type, options, order_by, keywords_index, partial_index, resource_type, resource_column, display_field, use_for_similar, iptc_equiv, display_template, tab_name, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, sync_field', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ref' => Yii::t('app', 'Ref'),
			'name' => Yii::t('app', 'Name'),
			'title' => Yii::t('app', 'Title'),
			'type' => Yii::t('app', 'Type'),
			'options' => Yii::t('app', 'Options'),
			'order_by' => Yii::t('app', 'Order By'),
			'keywords_index' => Yii::t('app', 'Keywords Index'),
			'partial_index' => Yii::t('app', 'Partial Index'),
			'resource_type' => Yii::t('app', 'Resource Type'),
			'resource_column' => Yii::t('app', 'Resource Column'),
			'display_field' => Yii::t('app', 'Display Field'),
			'use_for_similar' => Yii::t('app', 'Use For Similar'),
			'iptc_equiv' => Yii::t('app', 'Iptc Equiv'),
			'display_template' => Yii::t('app', 'Display Template'),
			'tab_name' => Yii::t('app', 'Tab Name'),
			'required' => Yii::t('app', 'Required'),
			'smart_theme_name' => Yii::t('app', 'Smart Theme Name'),
			'exiftool_field' => Yii::t('app', 'Exiftool Field'),
			'advanced_search' => Yii::t('app', 'Advanced Search'),
			'simple_search' => Yii::t('app', 'Simple Search'),
			'help_text' => Yii::t('app', 'Help Text'),
			'display_as_dropdown' => Yii::t('app', 'Display As Dropdown'),
			'external_user_access' => Yii::t('app', 'External User Access'),
			'autocomplete_macro' => Yii::t('app', 'Autocomplete Macro'),
			'hide_when_uploading' => Yii::t('app', 'Hide When Uploading'),
			'hide_when_restricted' => Yii::t('app', 'Hide When Restricted'),
			'value_filter' => Yii::t('app', 'Value Filter'),
			'exiftool_filter' => Yii::t('app', 'Exiftool Filter'),
			'omit_when_copying' => Yii::t('app', 'Omit When Copying'),
			'tooltip_text' => Yii::t('app', 'Tooltip Text'),
			'regexp_filter' => Yii::t('app', 'Regexp Filter'),
			'sync_field' => Yii::t('app', 'Sync Field'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ref', $this->ref);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('type', $this->type);
		$criteria->compare('options', $this->options, true);
		$criteria->compare('order_by', $this->order_by);
		$criteria->compare('keywords_index', $this->keywords_index);
		$criteria->compare('partial_index', $this->partial_index);
		$criteria->compare('resource_type', $this->resource_type);
		$criteria->compare('resource_column', $this->resource_column, true);
		$criteria->compare('display_field', $this->display_field);
		$criteria->compare('use_for_similar', $this->use_for_similar);
		$criteria->compare('iptc_equiv', $this->iptc_equiv, true);
		$criteria->compare('display_template', $this->display_template, true);
		$criteria->compare('tab_name', $this->tab_name, true);
		$criteria->compare('required', $this->required);
		$criteria->compare('smart_theme_name', $this->smart_theme_name, true);
		$criteria->compare('exiftool_field', $this->exiftool_field, true);
		$criteria->compare('advanced_search', $this->advanced_search);
		$criteria->compare('simple_search', $this->simple_search);
		$criteria->compare('help_text', $this->help_text, true);
		$criteria->compare('display_as_dropdown', $this->display_as_dropdown);
		$criteria->compare('external_user_access', $this->external_user_access);
		$criteria->compare('autocomplete_macro', $this->autocomplete_macro, true);
		$criteria->compare('hide_when_uploading', $this->hide_when_uploading);
		$criteria->compare('hide_when_restricted', $this->hide_when_restricted);
		$criteria->compare('value_filter', $this->value_filter, true);
		$criteria->compare('exiftool_filter', $this->exiftool_filter, true);
		$criteria->compare('omit_when_copying', $this->omit_when_copying);
		$criteria->compare('tooltip_text', $this->tooltip_text, true);
		$criteria->compare('regexp_filter', $this->regexp_filter, true);
		$criteria->compare('sync_field', $this->sync_field);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
