<?php

/**
 * This is the model base class for the table "undo_step".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UndoStep".
 *
 * Columns in table "undo_step" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $transaction_id
 * @property integer $field_id
 * @property string $original_value
 *
 */
abstract class BaseUndoStep extends TwigActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'undo_step';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UndoStep|UndoSteps', $n);
	}

	public static function representingColumn() {
		return 'original_value';
	}

	public function rules() {
		return array(
			array('transaction_id, field_id', 'numerical', 'integerOnly'=>true),
			array('original_value', 'safe'),
			array('transaction_id, field_id, original_value', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, transaction_id, field_id, original_value', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'transaction_id' => Yii::t('app', 'Transaction'),
			'field_id' => Yii::t('app', 'Field'),
			'original_value' => Yii::t('app', 'Original Value'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('transaction_id', $this->transaction_id);
		$criteria->compare('field_id', $this->field_id);
		$criteria->compare('original_value', $this->original_value, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
