<?php

/**
 * This is the model base class for the table "keyword".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Keyword".
 *
 * Columns in table "keyword" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $ref
 * @property string $keyword
 * @property string $soundex
 * @property integer $hit_count
 *
 */
abstract class BaseKeyword extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'keyword';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Keyword|Keywords', $n);
	}

	public static function representingColumn() {
		return 'keyword';
	}

	public function rules() {
		return array(
			array('hit_count', 'numerical', 'integerOnly'=>true),
			array('keyword', 'length', 'max'=>100),
			array('soundex', 'length', 'max'=>50),
			array('keyword, soundex, hit_count', 'default', 'setOnEmpty' => true, 'value' => null),
			array('ref, keyword, soundex, hit_count', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ref' => Yii::t('app', 'Ref'),
			'keyword' => Yii::t('app', 'Keyword'),
			'soundex' => Yii::t('app', 'Soundex'),
			'hit_count' => Yii::t('app', 'Hit Count'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ref', $this->ref);
		$criteria->compare('keyword', $this->keyword, true);
		$criteria->compare('soundex', $this->soundex, true);
		$criteria->compare('hit_count', $this->hit_count);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
