<?php

/**
 * This is the model base class for the table "info_text".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InfoText".
 *
 * Columns in table "info_text" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $code
 * @property string $text
 * @property string $html
 *
 */
abstract class BaseInfoText extends TwigActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'info_text';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InfoText|InfoTexts', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code', 'length', 'max'=>255),
			array('text, html', 'safe'),
			array('code, text, html', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, text, html', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'text' => Yii::t('app', 'Text'),
			'html' => Yii::t('app', 'Html'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('text', $this->text, true);
		$criteria->compare('html', $this->html, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
