<?php

/**
 * This is the model base class for the table "file_check".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FileCheck".
 *
 * Columns in table "file_check" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $filename
 * @property string $path
 * @property string $md5
 * @property string $creation_date
 * @property string $last_checked_date
 * @property integer $resource_id
 * @property string $alternate_files_json
 * @property integer $is_valid
 * @property string $info_json
 * @property string $error_json
 *
 */
abstract class BaseFileCheck extends TwigActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'file_check';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FileCheck|FileChecks', $n);
	}

	public static function representingColumn() {
		return 'filename';
	}

	public function rules() {
		return array(
			array('resource_id, is_valid', 'numerical', 'integerOnly'=>true),
			array('filename, path, md5', 'length', 'max'=>255),
			array('creation_date, last_checked_date, alternate_files_json, info_json, error_json', 'safe'),
			array('filename, path, md5, creation_date, last_checked_date, resource_id, alternate_files_json, is_valid, info_json, error_json', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, filename, path, md5, creation_date, last_checked_date, resource_id, alternate_files_json, is_valid, info_json, error_json', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'filename' => Yii::t('app', 'Filename'),
			'path' => Yii::t('app', 'Path'),
			'md5' => Yii::t('app', 'Md5'),
			'creation_date' => Yii::t('app', 'Creation Date'),
			'last_checked_date' => Yii::t('app', 'Last Checked Date'),
			'resource_id' => Yii::t('app', 'Resource'),
			'alternate_files_json' => Yii::t('app', 'Alternate Files Json'),
			'is_valid' => Yii::t('app', 'Is Valid'),
			'info_json' => Yii::t('app', 'Info Json'),
			'error_json' => Yii::t('app', 'Error Json'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('filename', $this->filename, true);
		$criteria->compare('path', $this->path, true);
		$criteria->compare('md5', $this->md5, true);
		$criteria->compare('creation_date', $this->creation_date, true);
		$criteria->compare('last_checked_date', $this->last_checked_date, true);
		$criteria->compare('resource_id', $this->resource_id);
		$criteria->compare('alternate_files_json', $this->alternate_files_json, true);
		$criteria->compare('is_valid', $this->is_valid);
		$criteria->compare('info_json', $this->info_json, true);
		$criteria->compare('error_json', $this->error_json, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
