<?php

/**
 * This is the model base class for the table "resource_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResourceType".
 *
 * Columns in table "resource_type" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $ref
 * @property string $name
 * @property string $allowed_extensions
 * @property integer $order_by
 *
 */
abstract class BaseResourceType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'resource_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ResourceType|ResourceTypes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('order_by', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('allowed_extensions', 'safe'),
			array('name, allowed_extensions, order_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('ref, name, allowed_extensions, order_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ref' => Yii::t('app', 'Ref'),
			'name' => Yii::t('app', 'Name'),
			'allowed_extensions' => Yii::t('app', 'Allowed Extensions'),
			'order_by' => Yii::t('app', 'Order By'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ref', $this->ref);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('allowed_extensions', $this->allowed_extensions, true);
		$criteria->compare('order_by', $this->order_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
