<?php
/**
	* Generated by ResourceSpace model
	* do not changes this file, update the modelFile
 */

class AgentBase extends RSRecordModel {


	protected $_modelName = 'Agent';
	protected $_typeId = 4;
	protected $_defaultSearchOrder = null;

	public function getTypeId() {
		return $this->_typeId;
	}

	protected $_fieldDefs = array(
		'143' => 'name',
		'144' => 'born',
		'145' => 'biography',
		'146' => 'internal_notes',
		'147' => 'contact_information',
		'149' => 'notes',
		'158' => 'deceased',
		'159' => 'email',
		'160' => 'url',
		'161' => 'address',
		'162' => 'telephone',
		'163' => 'gender',
		'168' => 'is_login_active',
		'169' => 'artist_login_id',
		'170' => 'artist_invite_message',
		'171' => 'login_name',
		'172' => 'login_email',
	);

	protected $_fieldInfo = array(
		'name' => array(
			'typeId' => '0',
			'options' => null,
		),
		'born' => array(
			'typeId' => '10',
			'options' => null,
		),
		'biography' => array(
			'typeId' => '1',
			'options' => null,
		),
		'internal_notes' => array(
			'typeId' => '1',
			'options' => null,
		),
		'contact_information' => array(
			'typeId' => '1',
			'options' => null,
		),
		'notes' => array(
			'typeId' => '1',
			'options' => null,
		),
		'deceased' => array(
			'typeId' => '0',
			'options' => null,
		),
		'email' => array(
			'typeId' => '',
			'options' => null,
		),
		'url' => array(
			'typeId' => '',
			'options' => null,
		),
		'address' => array(
			'typeId' => '',
			'options' => null,
		),
		'telephone' => array(
			'typeId' => '',
			'options' => null,
		),
		'gender' => array(
			'typeId' => '3',
			'options' => array('', 'Male', 'Female'),
		),
		'is_login_active' => array(
			'typeId' => '2',
			'options' => array('No', 'Yes'),
		),
		'artist_login_id' => array(
			'typeId' => '2',
			'options' => null,
		),
		'artist_invite_message' => array(
			'typeId' => '5',
			'options' => null,
		),
		'login_name' => array(
			'typeId' => '1',
			'options' => null,
		),
		'login_email' => array(
			'typeId' => '1',
			'options' => null,
		),
	);

	/**
	 *
	 * fields stored in the Keyword, ResourceKeyword tables
	 */
	protected $_keywordFields = array(
		'name' => true,
	);

	public function rules() {
		return array(
			array('name,born,biography,internal_notes,contact_information,notes,deceased,email'.
			',url,address,telephone,gender,is_login_active,artist_login_id,artist_invite_message,login_name,login_email', 'safe'));
	}

	public function search()
	{
		$criteria = new RSCriteria;

		$criteria->compare('name', $this->name, true);

		$criteria->compare('born', $this->born, true);

		$criteria->compare('biography', $this->biography, true);

		$criteria->compare('internal_notes', $this->internal_notes, true);

		$criteria->compare('contact_information', $this->contact_information, true);

		$criteria->compare('notes', $this->notes, true);

		$criteria->compare('deceased', $this->deceased, true);

		$criteria->compare('email', $this->email, true);

		$criteria->compare('url', $this->url, true);

		$criteria->compare('address', $this->address, true);

		$criteria->compare('telephone', $this->telephone, true);

		$criteria->compare('gender', $this->gender, true);

		$criteria->compare('is_login_active', $this->is_login_active, true);

		$criteria->compare('artist_login_id', $this->artist_login_id, true);

		$criteria->compare('artist_invite_message', $this->artist_invite_message, true);

		$criteria->compare('login_name', $this->login_name, true);

		$criteria->compare('login_email', $this->login_email, true);

		$this->beforeSearch($criteria);
		if ($this->_defaultSearchOrder != null) {
			return new RSDataProvider($this, array(
				'criteria' => $criteria,
				'order'=>$this->_defaultSearchOrder,
				'pagination'=>array('pageSize'=>$this->pageSize)));
		 } else {
			return new RSDataProvider($this, array(
				'criteria' => $criteria,
				'pagination'=>array('pageSize'=>$this->pageSize)));
		}
	}

}